# Generated by Django 4.1.6 on 2023-02-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_search_parameters_exclude_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
